/* INVENTARIOS · pantallas del módulo (GI-xx, maestros y Solicitudes de Pedido GP-xx) */
Object.assign(BC,{
 gi19:"Configuraciones / <b>Series de Documentos</b> · GI-19",
 gi00:"<b>Panel de Logística</b> · GI-00",
 gi18:"<b>Rotación de Artículos</b> · GI-18",
 gi17:"Maestros / <b>Listas de Materiales</b> · GI-17",
 gi17f:"Maestros / Listas de Materiales / <b>Lista</b> · GI-17",
 gi01:"Maestros / <b>Artículos</b> · GI-01",
 gi02:"Maestros / Artículos / <b>Formulario de Artículo</b> · GI-02",
 gi03:"Maestros / <b>Almacenes</b> · GI-03",
 gi04:"Maestros / Almacenes / <b>Formulario de Almacén</b> · GI-04",
 gi05:"<b>Inventario - Existencias</b> · GI-05",
 gi06:"<b>Kardex</b> · GI-06",
 gi07:"<b>Movimientos</b> · GI-07",
 gi08:"Movimientos / <b>Detalle de Movimiento</b> · GI-08",
 gi09:"Movimientos / <b>Crear Ingreso</b> · GI-09",
 gi10:"Movimientos / <b>Crear Salida</b> · GI-10",
 gi11:"Movimientos / <b>Solicitud de Transferencia</b> · GI-11",
 gi13:"<b>Solicitudes de Materiales</b> · GI-13",
 gi13f:"Solicitudes de Materiales / <b>Solicitud</b> · GI-13",
 gi14:"<b>Guías de Remisión Electrónicas</b> · GI-14",
 gi15:"Guías de Remisión Electrónicas / <b>Nueva GRE</b> · GI-15",
 gi16:"Guías de Remisión Electrónicas / <b>Detalle de GRE</b> · GI-16",
 gi20:"<b>Saldos por Fecha</b> · GI-20",
 mcfg:"Configuraciones / <b>Configuración General</b> · GI-CFG",
 mtipos:"Configuraciones / <b>Grupos de Artículo</b>",
 grupo:"Configuraciones / <b>Grupo de Artículo</b>",
 mcat:"Configuraciones / <b>Categorías</b>",
 msub:"Configuraciones / <b>Sub categorías</b>",
 mum:"Configuraciones / <b>Unidades de Medida</b>",
 mconv:"Configuraciones / <b>Conversiones de UM</b>",
 matr:"Configuraciones / <b>Atributos</b>",
 mbc:"Configuraciones / <b>Tipos de Código de Barra</b>",
 msede:"Configuraciones / <b>Sedes</b>",
 gp01:"Pedidos / <b>Solicitudes de Pedido</b> · GP-01",
 gp03:"Pedidos / Solicitudes / <b>Solicitud de Pedido</b> · GP-03"
});
Object.assign(NAVMAP,{gi19:"gi19",gi00:"gi00",gi18:"gi18",gi17:"gi17",gi17f:"gi17",gi01:"gi01",gi02:"gi01",gi03:"gi03",gi04:"gi03",gi05:"gi05",gi06:"gi06",gi07:"gi07",gi08:"gi07",gi09:"gi07",gi10:"gi07",gi11:"gi07",gi13f:"gi13",gi15:"gi14",gi16:"gi14",gi13:"gi13",gi14:"gi14",gi20:"gi20",mcfg:"mcfg",mtipos:"mtipos",grupo:"mtipos",mcat:"mcat",msub:"msub",mum:"mum",mconv:"mconv",matr:"matr",mbc:"mbc",msede:"msede",gp01:"gp01",gp03:"gp01"});
Object.assign(MST_KEYS,{mtipos:"tipos",mcat:"cat",msub:"sub",mum:"um",mconv:"conv",matr:"atr",mbc:"bc",msede:"sede"});
